title: Photography, Computation & Place
description: Workshop for Negev School of Architecture, December 2022
theme: just-the-docs

url: https://taipinc.github.io/negev2022

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - kramdown
