title: Photography, Computation & Place
description: Workshop for Negev School of Architecture, December 2022
theme: just-the-docs

url: https://taipinc.github.io/negev2022

aux_links:

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
