title: Photography, Computation & Place
description: Workshop for Negev School of Architecture, December 2022
theme: just-the-docs

url: https://taipinc.github.io/negev2022

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
